DROP DATABASE IF EXISTS EtsyReviews;
CREATE DATABASE EtsyReviews;
USE EtsyReviews;

DROP TABLE IF EXISTS reviews;
CREATE TABLE reviews (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  text TEXT NOT NULL,
  rating INTEGER NOT NULL,
  date DATE NOT NULL,
  product_id INTEGER NOT NULL,
  user_profile_url VARCHAR(250) NOT NULL
);