const connection = require('./index.js');

const queryString = `
DROP DATABASE IF EXISTS FEC1;CREATE DATABASE FEC1;
USE FEC1;
DROP TABLE IF EXISTS reviews;
CREATE TABLE reviews (id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50) NOT NULL,\`text\` TEXT NOT NULL,rating INTEGER NOT NULL,\`date\` DATE NOT NULL,product_id INTEGER NOT NULL,user_profile_url VARCHAR(250) NOT NULL,store_id INTEGER NOT NULL);
`;

connection.query(queryString, (err) => {
  if (err) {
    throw err;
  } else {
    const inserts = ["insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (1, 'bbilsford0', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 5, '2019-09-15', 17, 'http://diigo.com', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (2, 'cmanning1', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 4, '2019-04-25', 6, 'http://cbslocal.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (3, 'jcadwallader2', 'Nulla nisl. Nunc nisl.', 3, '2017-06-04', 10, 'https://dagondesign.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (4, 'sivanenko3', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 3, '2020-02-16', 14, 'https://feedburner.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (5, 'mocrevan4', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 4, '2017-07-28', 4, 'http://skyrock.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (6, 'mbrothwell5', 'Suspendisse ornare consequat lectus.', 5, '2018-01-26', 20, 'https://cpanel.net', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (7, 'awharlton6', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 4, '2019-03-07', 3, 'https://vistaprint.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (8, 'aelcombe7', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 5, '2017-07-25', 8, 'http://naver.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (9, 'fstrewther8', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 4, '2017-12-26', 8, 'https://blogs.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (10, 'cfettiplace9', 'Morbi a ipsum.', 4, '2019-12-21', 3, 'http://alexa.com', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (11, 'ftwaitsa', 'Morbi porttitor lorem id ligula.', 4, '2018-03-18', 3, 'https://pbs.org', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (12, 'bsleafordb', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 4, '2017-05-15', 13, 'https://canalblog.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (13, 'kyellowleesc', 'Donec posuere metus vitae ipsum. Aliquam non mauris.', 5, '2019-06-21', 19, 'https://princeton.edu', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (14, 'imadgwickd', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 3, '2019-03-05', 17, 'http://indiegogo.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (15, 'mtapplye', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 4, '2018-10-27', 16, 'http://clickbank.net', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (16, 'echatelf', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 5, '2018-12-10', 15, 'http://deliciousdays.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (17, 'wwoolastong', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 5, '2018-12-20', 9, 'https://china.com.cn', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (18, 'fmcnyscheh', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 4, '2018-04-05', 9, 'http://sciencedaily.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (19, 'kbydawayi', 'Suspendisse potenti.', 5, '2017-12-15', 2, 'https://trellian.com', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (20, 'rbeej', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 2, '2020-04-04', 10, 'https://xing.com', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (21, 'wstreaderk', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 1, '2017-11-20', 11, 'http://behance.net', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (22, 'bculkinl', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 4, '2018-07-22', 15, 'https://i2i.jp', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (23, 'ahallifaxm', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 4, '2019-10-12', 17, 'https://tuttocitta.it', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (24, 'dcozinsn', 'Etiam justo. Etiam pretium iaculis justo.', 4, '2017-01-14', 14, 'http://over-blog.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (25, 'vbortolomeio', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 3, '2016-11-13', 12, 'https://dion.ne.jp', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (26, 'bpringerp', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 5, '2015-08-31', 11, 'http://dion.ne.jp', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (27, 'nbockmannq', 'Etiam faucibus cursus urna.', 4, '2018-01-25', 8, 'http://surveymonkey.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (28, 'mburrelr', 'Proin risus. Praesent lectus.', 5, '2020-06-22', 16, 'http://nps.gov', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (29, 'jsuffes', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 1, '2018-05-24', 16, 'http://hp.com', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (30, 'zcapeyt', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 4, '2019-02-02', 13, 'https://soup.io', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (31, 'dblaskettu', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1, '2017-12-25', 19, 'https://forbes.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (32, 'mjacmarv', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 1, '2017-02-18', 13, 'http://google.de', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (33, 'bbarnbrookw', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 5, '2020-02-25', 20, 'https://dropbox.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (34, 'rdarbyx', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 5, '2017-01-20', 12, 'http://jimdo.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (35, 'dbreinleiny', 'Nullam varius.', 4, '2018-07-14', 17, 'http://angelfire.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (36, 'bgebbez', 'Pellentesque viverra pede ac diam.', 5, '2017-01-16', 19, 'http://nymag.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (37, 'wbearsmore10', 'Suspendisse potenti.', 5, '2019-09-27', 20, 'http://latimes.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (38, 'bsergean11', 'In eleifend quam a odio. In hac habitasse platea dictumst.', 5, '2018-09-27', 8, 'http://cargocollective.com', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (39, 'hgabbot12', 'Aliquam sit amet diam in magna bibendum imperdiet.', 3, '2017-01-23', 9, 'https://etsy.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (40, 'gdumigan13', 'Phasellus in felis.', 5, '2017-11-07', 2, 'https://biglobe.ne.jp', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (41, 'rrymour14', 'Curabitur convallis.', 3, '2019-07-13', 4, 'http://nifty.com', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (42, 'dboyington15', 'Nulla ut erat id mauris vulputate elementum.', 3, '2019-07-11', 11, 'https://topsy.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (43, 'ddomone16', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 3, '2019-07-31', 16, 'http://icq.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (44, 'wbackshaw17', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 4, '2018-08-23', 10, 'https://wordpress.org', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (45, 'pphizackerly18', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 5, '2016-04-24', 11, 'https://e-recht24.de', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (46, 'dhurford19', 'Proin eu mi. Nulla ac enim.', 5, '2017-08-30', 10, 'https://cnn.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (47, 'tprozescky1a', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 4, '2019-03-14', 15, 'https://free.fr', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (48, 'tdunphie1b', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 4, '2018-06-28', 3, 'https://bluehost.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (49, 'slayfield1c', 'Curabitur in libero ut massa volutpat convallis.', 5, '2018-10-07', 1, 'http://odnoklassniki.ru', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (50, 'cmcgavin1d', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 5, '2017-09-05', 6, 'http://xinhuanet.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (51, 'asmeall1e', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 4, '2018-10-08', 18, 'http://dedecms.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (52, 'sstode1f', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 5, '2018-04-26', 14, 'http://hexun.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (53, 'ctemperton1g', 'Etiam vel augue. Vestibulum rutrum rutrum neque.', 5, '2017-08-19', 11, 'http://bloglovin.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (54, 'krubes1h', 'Vestibulum sed magna at nunc commodo placerat.', 5, '2018-04-16', 20, 'https://sfgate.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (55, 'mwitton1i', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 5, '2019-10-23', 17, 'http://bandcamp.com', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (56, 'imacrinn1j', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 5, '2020-01-02', 18, 'http://youtube.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (57, 'iattenbrough1k', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 3, '2018-07-06', 5, 'http://behance.net', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (58, 'pdodwell1l', 'Fusce posuere felis sed lacus.', 5, '2018-07-03', 20, 'https://addtoany.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (59, 'kbirdwhistell1m', 'Nulla ac enim.', 3, '2019-01-20', 18, 'https://ovh.net', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (60, 'bwhitehall1n', 'Nulla facilisi.', 5, '2018-06-06', 1, 'http://zimbio.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (61, 'gblackborne1o', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 5, '2015-12-31', 10, 'http://jiathis.com', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (62, 'ekenningham1p', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 5, '2016-02-08', 10, 'https://cocolog-nifty.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (63, 'cmccallion1q', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 5, '2018-07-08', 11, 'https://blogs.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (64, 'mtenman1r', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 2, '2017-08-03', 4, 'http://xing.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (65, 'ystopforth1s', 'Duis at velit eu est congue elementum.', 3, '2017-09-20', 2, 'https://ehow.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (66, 'mchatwin1t', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 5, '2017-12-14', 15, 'http://scientificamerican.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (67, 'imersey1u', 'Suspendisse potenti. In eleifend quam a odio.', 5, '2019-05-05', 1, 'https://oracle.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (68, 'jcleave1v', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 5, '2019-05-23', 2, 'https://tripod.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (69, 'palwin1w', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 5, '2015-12-20', 7, 'http://disqus.com', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (70, 'gyokley1x', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 4, '2017-08-07', 15, 'https://patch.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (71, 'mhildrew1y', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 3, '2019-09-23', 3, 'https://issuu.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (72, 'ghurrell1z', 'Ut at dolor quis odio consequat varius.', 5, '2020-07-12', 17, 'https://va.gov', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (73, 'mfurley20', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 4, '2018-02-11', 3, 'http://php.net', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (74, 'ftomes21', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 4, '2017-12-06', 14, 'http://boston.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (75, 'lthorius22', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 5, '2019-04-27', 6, 'http://freewebs.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (76, 'jhurlin23', 'Duis aliquam convallis nunc.', 5, '2016-06-11', 18, 'https://clickbank.net', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (77, 'ccrossgrove24', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', 4, '2019-05-14', 15, 'https://about.com', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (78, 'gpoynzer25', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 4, '2015-09-17', 15, 'https://linkedin.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (79, 'stomasoni26', 'Nulla mollis molestie lorem. Quisque ut erat.', 4, '2015-08-19', 19, 'http://myspace.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (80, 'skillich27', 'Donec posuere metus vitae ipsum. Aliquam non mauris.', 4, '2018-04-02', 2, 'https://harvard.edu', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (81, 'afroggatt28', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 5, '2020-02-24', 20, 'https://e-recht24.de', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (82, 'czamora29', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 4, '2017-09-18', 3, 'https://alexa.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (83, 'sshellshear2a', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 5, '2016-08-28', 20, 'https://flickr.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (84, 'enolda2b', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 4, '2019-07-17', 11, 'http://timesonline.co.uk', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (85, 'itootell2c', 'Nullam varius.', 5, '2020-05-29', 20, 'http://tinypic.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (86, 'mburkart2d', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 5, '2019-03-19', 12, 'https://nih.gov', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (87, 'cthowes2e', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 5, '2017-02-03', 4, 'http://infoseek.co.jp', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (88, 'kgheorghescu2f', 'Nunc purus.', 5, '2015-10-26', 13, 'http://imageshack.us', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (89, 'ctothe2g', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 5, '2018-06-17', 13, 'https://bloomberg.com', 3)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (90, 'bteaz2h', 'Phasellus in felis. Donec semper sapien a libero.', 4, '2020-02-19', 3, 'http://google.ca', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (91, 'gfranzen2i', 'Donec vitae nisi.', 3, '2017-02-26', 19, 'http://mysql.com', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (92, 'kcaudell2j', 'Suspendisse accumsan tortor quis turpis.', 4, '2016-08-31', 6, 'https://pinterest.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (93, 'btoner2k', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 3, '2016-11-20', 16, 'https://webmd.com', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (94, 'japted2l', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 3, '2017-11-18', 3, 'http://shinystat.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (95, 'tbarnhart2m', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 4, '2017-08-30', 10, 'http://utexas.edu', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (96, 'egreep2n', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 4, '2019-08-31', 16, 'http://amazon.co.jp', 1)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (97, 'bpretsell2o', 'Curabitur in libero ut massa volutpat convallis.', 2, '2016-07-06', 6, 'https://archive.org', 2)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (98, 'vwyley2p', 'Proin eu mi.', 5, '2019-03-05', 12, 'http://uol.com.br', 4)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (99, 'dbohlens2q', 'Proin risus.', 5, '2018-10-11', 5, 'http://cisco.com', 5)",
      "insert into reviews (id, username, text, rating, date, product_id, user_profile_url, store_id) values (100, 'pgallihaulk2r', 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 5, '2016-05-06', 2, 'https://com.com', 5)",
    ];

    const queryStrings = inserts.join(';');

    connection.query(queryStrings, (error, result) => {
      if (error) {
        throw error;
      } else {
        for (let i = 0; i < result.length; i += 1) {
          console.log(`A review with id ${result[i].insertId} was inserted.`);
        }
      }
      connection.end();
    });
  }
});
